/geode2/home/u080/skarukas/Carbonate/SITH/models/logpolar/lptransform.py:158: UserWarning: Use of index_put_ on expanded tensors is deprecated. Please clone() the tensor before performing this operation. This also applies to advanced indexing e.g. tensor[indices] = tensor (Triggered internally at  ../aten/src/ATen/native/TensorAdvancedIndexing.cpp:395.)
  tau[tau <= 0] = 0
Epoch:   0%|          | 0/40 [00:00<?, ?it/s]
Batch:   0%|          | 0/1563 [00:00<?, ?it/s][A
                                               [AEpoch:   0%|          | 0/40 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "/geode2/home/u080/skarukas/Carbonate/SITH/train.py", line 222, in <module>
    train_loop(model, train_dataloader, config, val_dataloader)
  File "/geode2/home/u080/skarukas/Carbonate/SITH/train.py", line 46, in train_loop
    prediction = model(X)
  File "/N/soft/sles15/deeplearning/Python-3.9.7/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/geode2/home/u080/skarukas/Carbonate/SITH/models/DeepLogPolarClassifier.py", line 60, in forward
    out = self._forward_batch(inp)
  File "/geode2/home/u080/skarukas/Carbonate/SITH/models/DeepLogPolarClassifier.py", line 95, in _forward_batch
    x = self.lpconv_layers[i](x)
  File "/N/soft/sles15/deeplearning/Python-3.9.7/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/geode2/home/u080/skarukas/Carbonate/SITH/models/logpolar/layers.py", line 184, in forward
    inp = self.lpconv(inp)
  File "/N/soft/sles15/deeplearning/Python-3.9.7/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/geode2/home/u080/skarukas/Carbonate/SITH/models/logpolar/layers.py", line 125, in forward
    x = self.topk(x)
  File "/N/soft/sles15/deeplearning/Python-3.9.7/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/geode2/home/u080/skarukas/Carbonate/SITH/models/other_layers/TopKPool.py", line 38, in forward
    i = torch.sort(i, self.dim).values
RuntimeError: CUDA out of memory. Tried to allocate 4.66 GiB (GPU 0; 39.59 GiB total capacity; 30.29 GiB already allocated; 1.87 GiB free; 35.87 GiB reserved in total by PyTorch)
